CREATE TABLE books (id INTEGER PRIMARY KEY,name TEXT,rating INTEGER );

INSERT INTO books VALUES (1,"PYTHON",4);
INSERT INTO books VALUES (2,"C PROGRAM",4);
INSERT INTO books VALUES (3,"RUBY",4);


SELECT * FROM books
